travis:
  secure:
    BINSTAR_TOKEN: A7Przy4xbzAMa+o/1SSMPBt8ruQrGw+us19sVi30y2LlhzZip5S4mFhaDdmRIG3/MGipnQL41Fjxd24BLjQOK06VALN8Vmyk97ak3zDVT7qt7UFfDEtsQ895zOa8r0e3F4JUZ+KzhovpCxbZrdr2HQ29+DfWG+CRckObAMsSg58aSp1IluZeVqh7DY1iCCAe0sFzkj7Vhr0ngCAvTuB7W3xesyLQxzAnGe39Ex03zzsj4NkY50rXpT+hpHN6nn33vIG86PhxdvJaHObbHs8+yhI/L5iTpWC/JytQazuIVsCVnPfAxfAdluq5RvOu1BDKOmLdsnMkqsyZ2FUxpOiLBaMigIcx43tFV3EsjTGyf2qOLp6Ez5+e/7nu/oUE4UWTUYgh5t6FrFQZAQ/IT6ML3ZPJhtkl+PByvTIG+wXlWEz4e83Kqk3LxrHVmCy1in4pA9CtlDWlOVhmgQ4hQbLeeFfVp3yD8/uDfOUe3w/UY0B2w5jCXDmg9MaQYhCWLpNIVBqbh+qyUnETR2RYChXlaAM46oY7s24N9SIsJwuM+8hajyEErZau6G0vz0HVHESA5XTUtb35Vp+CjluEWy+uDoyPSPtT8k/zis3KH27GQjA0POcjBTqcFGMmYlRZKIznzDLIu4r8DOuhyBD8cCEC+v72jv70iQ9cry457lODvn0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
