travis:
  secure:
    BINSTAR_TOKEN: Bms7FmNdfgEEo1DYV87xw5SdRqOP3ZRKtXJn1Qt9t5jMTMUNccgP1rRxrC6mdWrBdjf8HhDSaiSQn91L5Gv6x6Os+zsDYgal2ZOHcxjUh2FKOjYK8hmHQ8h2fA/FySeIUonInx4yxrzc5pg5tZc/ZQmZU2nIRNKZeTCU8fnhA6EGaWGXJmzhqTx9HXclQSpP3nokchMmK7GeUIjeYCgZevhwVOKRgPJnPxtv9sImLuCNNqO62JvN9D+QQKtPNudm0L2EBARzbEcmgbGrMfuIdYHu0enOSTBX+0KqNRQAuUBA/+tnaNN+wJ9c79Skkibg6UGCkzDB1SQrvO0nKGZfbdapt1l+U2oGC3kwvA009Wq546+Ecg4e+kHmYWtUqf3f0KIU229sBI4Pk2DE8+2ga3vnPpQD+4XmIEL58zeWMP9dP/0QqbM5OGQ+hYXQp9BUSgLnWKq9YDPWKDjP3h0TrxY2ZEM/I0uGt+x9Vzr8vD1BukpNrW8wXMO7zathnRu5Pzd4If7HFafw1kVmbOTqzY0Wvev3zPO+2WdQTRZ79Dtrijsfo/AyG1/T692HcSl/h91N+6llGot4HiPhP3ZFNLetQU1vm/S68w3rTYkqJ+I7QBfz7NpdHcEe6cEdY8rjX2PQ4m8AWZGLxk+g4Up4GMC2cKB0GlRUAKB7S/3z7YU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
